MarkDown file output support
koriym/app-state-diagram pull request #86
Opened 2021-11-18 11:03 UTC by koriym

2021-11-19 16:04 UTC, koriym commented
@NaokiTsuchiya レビューお願いします🙇🏻‍♂️

2021-11-20 04:53 UTC, NaokiTsuchiya requested changes

2021-11-20 04:53 UTC, NaokiTsuchiya commented on src/ConfigFactory.php
> +            $mode
`fromCommandLine` の方にも mode が必要ですかね

2021-11-20 04:53 UTC, NaokiTsuchiya commented on src/DumpDocs.php
> +    public function fileOutput(string $title, string $markDown, string $basePath, string $format): void
`private` で良さそうです！

2021-11-20 06:21 UTC, NaokiTsuchiya requested changes

2021-11-20 06:21 UTC, NaokiTsuchiya commented on src/DumpDocs.php
> +    public function fileOutput(string $title, string $markDown, string $basePath, string $format): void
```suggestion
    private function fileOutput(string $title, string $markDown, string $basePath, string $format): void
```

2021-11-20 07:15 UTC, koriym reviewed
dd

2021-11-20 07:22 UTC, NaokiTsuchiya commented on src/ConfigFactory.php
> +            $mode
@koriym これもお願いします！

2021-11-20 07:25 UTC, NaokiTsuchiya commented on src/ConfigFactory.php
> +            $mode
`./bin/asd --mode=markdown profile.xml`

2021-11-20 07:35 UTC, koriym commented on src/ConfigFactory.php
> +            $mode
```
% ./bin/asd --mode=markdown ./docs/blog/profile.xml
ASD generated. /Users/akihito/git/app-state-diagram/docs/blog/index.md
Descriptors(12), Links(6)
```
となります（？）

2021-11-20 08:03 UTC, NaokiTsuchiya approved these changes
👍

2021-11-20 08:21 UTC, merged